### ISSUE TITLE
Initial Vagrantfile

### ISSUE THREAD

**Issue by russleyshaw** [russleyshaw/kwiwk#5]
Vagrant is a cool tool to use when needing to do Linux development on a Windows machine. Rather than loading up a heavy VirtualBox instance with a GUI, Vagrant uses VirtualBox to spin up a terminal only VM. Vagrant instances automatically sync the current working directory with the `/vagrant` directory in the VM.
- [ ] Add a section to the README.md called `Using Vagrant` outlining how to install Vagrant on a Windows system and how to bring up the instance.

The Vagrantfile should be configured to:
- [x] use latest Ubuntu (16.10)  
- [x] install `cmake`, `gcc`, `clang`, `make`, `git`, `ncurses`, `gtest`  
- [x] link from `/vagrant` to `~/workspace` (for convenience)

**Comment by 2ajoyce** [comment]
Readme was not updated
